version: "3"
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  backend:
    build:
      dockerfile: Dockerfile
      context: ./src/backend

  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./src/frontend


